### ISSUE TITLE
Documentation update

### ISSUE THREAD

**Issue by dev1z** [torrust/torrust-tracker#45]
Please update the documentation as the code on torrust.com is incorrect (missing double `[[brackets]]`) and include more user friendly explanation of all new/old config options and how to use new mysql drivers

**Comment by mickvandijke** [comment]
Documentation will be updated today.

**Comment by dev1z** [comment]
Thanks didn't test it yet but but noticed gbitt is offline since you guys pushed update is it because of some error in code or misconfiguration? @Power2All @WarmBeer

**Comment by Power2All** [comment]
Yeah, that's why I'm rewriting the code from WARP to Actix.
Will take some time until we get a working version prepared, but it should have all the issues solved we have found while working on this.
Current server's memory limitation is hitting, because of a possible memory leak, so Linux is killing the process eventually.
Gbitt is up again, but yeah, it has a memory leak, so I'm working on a replacement asap, will let you know when we have a testing environment up.

**Comment by mickvandijke** [comment]
Docs have been updated to 2.3.0
