### ISSUE TITLE
Better peer ID recognition

### ISSUE THREAD

**Issue by si14** [torrust/torrust-tracker#475]
Hey folks!

I just released [a peer ID registry/parser](https://github.com/torrentdyne/tdyne-peer-id-registry) I was working on for my own [BitTorrent related project](https://torrentdyne.com). I think it can help Torrust to recognise [more clients](https://github.com/torrust/torrust-tracker/blob/14b1dca8f3fc12a484dd389f3f5268b7899fb019/src/tracker/peer.rs#L255) and also get their versions for free. Plus it'd be great to join our efforts on that kind of boring but foundational building blocks.

Let me know what you think, if you like the idea I'm happy to submit a PR changing the `get_client_name` implementation. It seems to be almost a drop-in replacement. I return `String`s instead of `'static &str`, but it should't be a problem as [the only call site](https://github.com/torrust/torrust-tracker/blob/14b1dca8f3fc12a484dd389f3f5268b7899fb019/src/servers/apis/v1/context/torrent/resources/peer.rs#L42) turns that `&str` into a `String` immediately anyway.

**Comment by josecelano** [comment]
> Hey folks!
> 
> I just released [a peer ID registry/parser](https://github.com/torrentdyne/tdyne-peer-id-registry) I was working on for my own [BitTorrent related project](https://torrentdyne.com). I think it can help Torrust to recognise [more clients](https://github.com/torrust/torrust-tracker/blob/14b1dca8f3fc12a484dd389f3f5268b7899fb019/src/tracker/peer.rs#L255) and also get their versions for free. Plus it'd be great to join our efforts on that kind of boring but foundational building blocks.
> 
> Let me know what you think, if you like the idea I'm happy to submit a PR changing the `get_client_name` implementation. It seems to be almost a drop-in replacement. I return `String`s instead of `'static &str`, but it should't be a problem as [the only call site](https://github.com/torrust/torrust-tracker/blob/14b1dca8f3fc12a484dd389f3f5268b7899fb019/src/servers/apis/v1/context/torrent/resources/peer.rs#L42) turns that `&str` into a `String` immediately anyway.

Hi @si14, I think it's a great idea. We have started contributing to other crates like [serde_bencode](https://github.com/toby/serde-bencode/pull/34). And we also want to extract some packages in the future, for example, for the [info_hash](https://github.com/torrust/torrust-tracker/issues/360). We totally agree we should join efforts for the basic building block so that PR would be very welcomed. In case you can't do it eventaually, I'll take a look after our next major release. We are now focused on releasing a new major version.

cc @da2ce7

**Comment by josecelano** [comment]
Close via https://github.com/torrust/torrust-tracker/pull/477
