### ISSUE TITLE
Error: Too many open files (os error 24)

### ISSUE THREAD

**Issue by babico** [torrust/torrust-tracker#72]
Hi after opening tracker it gives constant error about editing file. I think `data.db` its open, edit and not close after it, but I don't know Rust so I couldn't find any code about it. I try to solve with restarting server for now.
![image](https://babico.s-ul.eu/vIhuKwWp)

![image2](https://babico.s-ul.eu/k2MTUUxk)

**Comment by mickvandijke** [comment]
Hey @babico ,

Thank you for reporting this issue. I'll look into it.

**Comment by babico** [comment]
An update to the bug seems to have been fixed when I turn off the HTTP servers. Maybe on HTTP servers. BTW I haven't used the HTTP servers for around 20-25 days but it seems to affect the whole program.

![image2](https://babico.s-ul.eu/VWyDbC4t)
![image1](https://babico.s-ul.eu/b1QBKNIZ)

**Comment by Power2All** [comment]
That's a Linux issue, not a app issue.
@WarmBeer Basically, it's the Open Files limiter on Linux, which "could" be set in the ``/etc/security/limits.conf`` file to force a higher limit, or using the ``ulimit`` tool to raise it higher.
By default, Linux allows maximum of 1024 files to be open, and anything higher will be denied.
Since sockets are technically also "file descriptors", it counts as well.

You can close this on the fact that it isn't a program problem.

**Comment by babico** [comment]
Thanks for response I try the solution.
