### ISSUE TITLE
Create benchmarking tool/test for `udp` tracker.

### ISSUE THREAD

**Issue by mickvandijke** [torrust/torrust-tracker#87]

**Comment by greatest-ape** [comment]
I would recommend you to just use https://github.com/greatest-ape/aquatic/tree/master/crates/udp_load_test .

(edit by @da2ce7, fix link)

**Comment by josecelano** [comment]
Relates to: https://github.com/torrust/torrust-tracker/issues/496

**Comment by josecelano** [comment]
I'm getting this error running the lua script for the HTTP tracker:

```output
PANIC: unprotected error in call to Lua API (attempt to index a nil value)
```

Relates to: https://github.com/wg/wrk/issues/298

I'm going to remove that benchmarking tool and start using the aquatic load test commands. I've been using the [udp_load_test ](https://github.com/greatest-ape/aquatic/tree/master/crates/udp_load_test). I will update the documentation explaining how to use it.

**Comment by josecelano** [comment]
Hi @mickvandijke, I'm going to close this issue because we are using:

For E2E tests:

- Aquatic UDP load test
- Aquatic Bencher

For Unit tests (only the torrents repositories):

- @da2ce7 has added performance tests using Criterion in the [torrent-repository package](https://github.com/torrust/torrust-tracker/tree/develop/packages/torrent-repository).

Feel free to re-open it if there is something that you had in your mind when you opened the issue that is still missing.
